# **Python for Data science**

## **Integers and Floats**

In [ ]:
from math import sqrt

x,y,z = 4,5,6

length = sqrt(x**2+y**2+z**2)  # [or] (x**2+y**2+z**2)**0.5
print(length)

In [ ]:
amt = 1.2e6
salary = 9.3e5

salary -= salary*0.3
amt += salary

amt += amt*.04
amt -= 1.2e5

print(amt)

In [ ]:
mon = "500"
tue = "300"
wed = "200"
thu = "100"
fri = "400"
print(int(mon) + int(tue) + int(wed) + int(thu) + int(fri))

## **Strings**

In [ ]:
# 1) can use "" and '' accordingly

b = 'hello "world" hello'
a = "hello 'world' hello"

print(a)
print(b)

In [ ]:
# 2) here "\" is use after " and ' because it escape the character after it (considers the ' or " as string and escapes it ) [or] (2)

h = "hello \"world\" hello"

e = "hello \'world\' hello"

l = "hello \\world\\"       # (no need actually)
l1 = "hello \world\ "       # "hello \world\" --> error , the " or ' after \ , it includes " in the string and makes it look like open string

print(h)
print(e)
print(l)
print(l1+l)

hello "world" hello
hello 'world' hello
hello \world\
hello \world\ hello \world\

In [ ]:
a = "hello" + " " + "world"
b = "hello"*10

print(a)
print(b)

In [ ]:
name = input("Enter the name: ")
age = int(input("Enter the age: "))

print(f"name: {name} & age: {age}")
print("name: {} & age: {} ".format(name,age))

print("name: {x} & age: {y} ".format(x=age,y=name))

In [ ]:
model = "VGG16"
iteration = "150"
accuracy = "67.98"

print(f"The accuracy of {model} in {iteration} iteration is: {accuracy}%")

In [ ]:
given_name = "Thoyaja"
middle_name = "Vishwanatha"
family_name = "Gangadara"

name_length = given_name + " " + middle_name + " " + family_name


print(name_length[:21])    # whenever you want to cut a string

Thoyaja Vishwanatha G

In [ ]:
p = "hello World"

print(p.islower())
print(p.upper())
print(p.isupper())
print(p)

print(p.count("l"))   # counts no. of times a argument is repeated
print(p.find("o"))    # returns first "o"'s index
print(p.find("k"))    # default is -1, if argument is not found

## **Lists**

In [ ]:
student = ["hello", "zero", 3.6, 3, True]

print(student[0])
print(student[4])
print(student[-1])
print(student[-3])

print(student)

In [ ]:
j = ["sam", "pam", "rocky", "austin", "steve", "banner", 1, 2, 3, 7.5, True]

print(j[len(j) - 1])

In [ ]:
# Slicing in list (can be also in string)

j = ["sam", "pam", "rocky", "austin", "steve", "banner", 1, 2, 3, 7.5, True]

print(j[3:6])
print(j[:5])
print(j[6:])
print(j[-7:-3])            # Default: step = +1. so, cannot do reverse list

# Advanced Slicing [start:stop:step]
print()

print(j[::2])
print(j[3:9:2])
print(j[::-1])          # reverse the list
print(j[::-2])          # reverse the list + increament 2
print(j[-2:-8:-2])

In [ ]:
student = ["hello", "zero", "kaifs", "gsjjs", "fjjsnk"]

print(student[1][1])      # Accessing letter inside a string inside a list

print()
for i in student:
  print(i[0])

### **Membership Operator**

In [ ]:
a = "Hello World"

print("her" in a, not("llo" not in a), "or" not in a)

In [ ]:
student = ["hello", "zero", "kaifs", "gsjjs", "fjjsnk"]

print("llo" not in student, "kaifs" in student,"er" in student)

In [ ]:
# PROBLEM
# immutable: cannot modify the value.(but can be modified when its copy is created) eg: strings (when "=" it makes the copy of the original value
# i.e if changed in duplicate, original remains same [different locations])
# mutable: can modify the value. eg: lists, dic.. (when "=" it make the view of the original value i.e if changed in duplicate, original changes [same location])

a = "god"
b = a
print(id(b))    # location of b
print(b)
b = b + "less"
print(b)
print(id(b))
print(id(a))      # original didn't change for immutable data, when its copy is modified

print()

k = ["hello", "zero", "kaifs", "gsjjs", "fjjsnk"]
d = k
d[1] = "jimmy"
print(k)           # original also changed, when modified its copy.
print(id(k))
print(id(d))

In [ ]:
# SOLUTION: making a copy for mutable datatype
# shallow copy: only for single lists

g = ["hello", "zero", "kaifs", "gsjjs", "fjjsnk"]
s = g.copy()                                         # created copy of it which is in different memory location (which can be said that it is a proper copy)
s[1] = "peter"
print(s)
print(g)
print(id(s))
print(id(g))

In [ ]:
# deep copy: for nested lists

import copy

g = ["hello", "zero", "kaifs", ["gsjjs", "fjjsnk"]]
s = copy.deepcopy(g)
s[3][0] = "piggy"
print(s)
print(g)

In [ ]:
g = ["hello", "zero", "kaifs", "gsjjs", "fjjsnk"]

print(len(g))
print(max(g))
print(min(g))
print(sorted(g))     # but original list is same, and not sorted

print()

g.sort()            # sort() method permantly changes the origial list
print(g)

print()

print(" & ".join(g))     # join() structure --> seperator.join(list)

### x.method() is a method format(cannot be used in print). fun(x) is the function or can be constructor(can be used inside "print").

In [ ]:
j = ["sam", "pam", "rocky", "austin", "steve", "banner", 1, 2, 3, 7.5, True]

j.append("dawg")          # adds at the end of list and only takes 1 argument(can be in list or normal datatype)
j.insert(4,[3,7.24])
j.extend([3,4.9,"zero"])    # can joins lists at the end , which is not possible by "append"
print(j)

['sam', 'pam', 'rocky', 'austin', [3, 7.24], 'steve', 'banner', 1, 2, 3, 7.5, True, 'dawg', 3, 4.9, 'zero']

In [ ]:
lst1 = ["M", "Na","i","khu"]
lst2 = ["y","me","s","shboo"]

lst1[3] = lst1[3].title()                                 # [or] lst1[3].title() --> makes into title format.


for i in range(len(lst2)):
  lst1[i] = lst1[i] + lst2[i]                               # z = []
                                                            # for i in range(len(lst2)):
print(lst1)                                                 #    z.append(lst1[i] + lst2[i])

['My', 'Name', 'is', 'Khushboo']

## **Tuples and Dictionary**

### **list:** ordered & duplicate & mutable. **representation:** []
### **tuple:** ordered & duplicate & immutable --> cannot be modified i.e cannot give other variable (eg: x,g) to the location of the declared tuple in memory.
### **representation:** can use () or nothing
### **sets:** unordered & no duplicate & mutable --> can be modified. **representation:** {}
### **dict:** ordered & mutable & no duplicate. **representation:** {{ : },{ : }}. Has unique keys.

In [ ]:
lst = [10,200,[40,30,[60,70],80],12,56]

lst[2][2].append(47)
print(lst)

[10, 200, [40, 30, [60, 70, 47], 80], 12, 56]

### Always need to create new list when doing a function to a list [or] getting a list from modifying the elements in it. **[Exception]**

###Therefore, if you want to process/do operation each element in the list, we need to get a new list (can use map(), but there also we need to create new list). But if we need to modify a list as a whole, we can do by indexing. **[Exception]**

In [ ]:
# Exception Proof
st = [10,200,12,56]

for i in range(len(st)):
  st[i] = st[i] + 30

print(st)

[40, 230, 42, 86]

In [ ]:
d = {"H": 1,"He": 2, "Li": 3 , "Be": 4, "B": 5, "C": 6}

print(d.keys())
print(d.values())
print(d.items())      # return key-value in tupple format

print("K" in d)
print(d.get("Be"))                                 # gets its value, otherwise "None".     Format: dict.get(key,default=None)
print(d.get("F","this key is not available"))       # instead of "None" we can custom it to how we want.

print()

del d["B"]
print(d)

In [ ]:
# Compound Data structures
sta = {"H":{"no.":1,"weight":1.0073},
       "He":{"no.":1,"weight":4.026}}

print(sta.get("He").get("weight"))       # [or] print(sta["He"]["weight"])
print(sta["He"].get("no."))

In [ ]:
sample = {"class":{
    "student":{
        "name":"mike",
        "marks":{
            "physics": 80,
            "chemistry": 75
        }
    }}}

print(sample["class"]["student"]["marks"].get("physics"))

80

In [ ]:
x = {"Khushboo":{
    "age":23,
    "designation":"data scientist",
    "skills": ["python","sql","ml","dl","pyspark","R","Tableau"],
    "Introduction":"Hi, My name is Khushboo"
}}

x["Khushboo"]["age"] = str(x["Khushboo"]["age"])
x["Khushboo"]["Introduction"] = x["Khushboo"]["Introduction"].split()         # string.split() --> converts string to list according to the spaces between(default) .
                                                                              # And if we want to split at "o" letter --> string.split("o")
print(x)

{'Khushboo': {'age': '23', 'designation': 'data scientist', 'skills': ['python', 'sql', 'ml', 'dl', 'pyspark', 'R', 'Tableau'], 'Introduction': ['Hi,', 'My', 'name', 'is', 'Khushboo']}}

## **Conditional Statements**

### **"if-else" statement**

In [ ]:
bikeapp_balance = 29
bank_balance = 700

if bikeapp_balance < 100:
  if bank_balance > 500:
    bikeapp_balance += 500
    bank_balance -= 500
    print("recharged")
  else:
    print("insufficient balance")
else:
  print("no need of recharge")

In [ ]:
x = int(input("Enter the value: "))

if x % 2 == 0:
  print("even")
else:
  print("odd")

In [ ]:
marks = int(input("Enter the marks: "))

if marks >= 90:
  print("A+")
elif marks >= 80:
  print("A")
elif marks >= 70:
  print("B")
elif marks >= 60:
  print("C")
elif marks >= 50:
  print("D")
elif marks >= 40:
  print("E")
else:
  print("F")

In [ ]:
purchase_amount = int(input("Enter the Amount: "))
state = input().upper()                            #  (or) state = state.upper()


if state == "CA":
  print(purchase_amount + (7.5*purchase_amount)/100 )
elif state == "MN":
  print(purchase_amount + (9.5*purchase_amount)/100)
elif state == "NY":
   print(purchase_amount + (8.9*purchase_amount)/100)

### **Rules of "if-else" statement**

In [ ]:
season = "winter"

if season == "rain" or "hi":    # as season == "rain" is one condition and "hi" is another consition(as [or] or [and] seperate sonly conditions) also, string "hi" is always True.
     print("good season")       # NOTE: None, False, zer of any numberic type, empty sequence collection are considered as false.

In [ ]:
x = int(input("enter the number: "))

if x % 4 == 0:
  list = [str(x) + str(x**2), int(str(x*2) + str(x**2))]
else:
  list = [int(str(x) + str(x**3)), int(str(x*2) + str(x**3))]

print(list)

In [ ]:
x = int(input("enter the number: "))

if x > 0:
  print("positive")
elif x < 0:
  print("negative")
else:
  print(0)

In [ ]:
x = int(input("enter the number: "))

if x % 2 == 0 and x % 3 == 0:
  print("yes")
else:
  print("no")

In [ ]:
age = int(input("enter the number: "))

if age >= 18:
  print("eligible")
else:
  print("not eligible")

In [ ]:
x = int(input("enter the number: "))

if 99 < x < 999:
  print("yes")
else:
  print("no")

In [ ]:
x = int(input("enter the number: "))

week = x // 7
days = x % 7
print(f"week: {week} days: {days}")

### **for loops**

In [ ]:
for i in range(0,3):         # [or] range(3)
  for j in range(1,4):
    print(i,end="")    # no new line
    print(j)

In [ ]:
for i in range(0,3):          # [or] range(3)
  for j in range(2,7,2):
    print(str(i) + str(j**2))          # alternative of above syntax

In [ ]:
l = [2,3,4,5]
nl = []

for i in l:
  nl.append(i**2)
print(nl)

## **for loops contd**

In [ ]:
# Modifying of elements in list without creating new list

cities = ["new york city","mountain view","chicago","los angeles"]

for i in range(len(cities)):
  cities[i] = cities[i].upper()

print(cities)

['NEW YORK CITY', 'MOUNTAIN VIEW', 'CHICAGO', 'LOS ANGELES']

In [ ]:
names = ["Joey Tribbiani","Monica Geller","Chandler Bing", "Ross Geller","Phoebe Buffay "]

for i in range(len(names)):
  names[i] = names[i].lower().replace(" ", "_")             # string.replace("x","y") --> x with y in the string

print(names)

['joey_tribbiani', 'monica_geller', 'chandler_bing', 'ross_geller', 'phoebe_buffay_']

In [ ]:
tokens = ["<greeting>","Hello world","</greeting>"]                   # XML: data language similar to HTML and <(matter)> is a XML tag

count = 0
for i in tokens:
  if i[0] == "<" and i[-1] == ">":
    count += 1

print(count)

2

In [ ]:
items = ["first string","second string","third string"]

html_str = "<ul>\n"                     # "\n" in string gives a new line at where it is written

for i in items:
  html_str += "<li>" + i + "</li>\n"
html_str += "</ul>"

print(html_str)

<ul>
<li>first string</li>
<li>second string</li>
<li>third string</li>
</ul>

In [ ]:
result = 0
basket_items = {"apples": 4,"oranges": 19,"kites": 3, "Sandwiches": 8}
fruits =  ["apples","oranges","pears","peaches","grapes","bananas"]

for i in fruits:
  if i in basket_items.keys():
    basket_items[i] += 1
    result += basket_items[i]

print(basket_items)
print(result)

{'apples': 5, 'oranges': 20, 'kites': 3, 'Sandwiches': 8}
25

## **while loops**

In [ ]:
i = 0
while i < 3:
  j = 0
  while j < 4:
    print(i,end="")
    print(j)
    j += 1
  i += 1

In [ ]:
i = int(input("Enter the number for factorial: " ))
j = 1
while i > 0:
  j *= i
  i -= 1

print(j)

In [ ]:
# zip : it is a method which attaches elements in different lists

x = ["villian", "hero", "lion", "pig","dog"]
y = [150, 100, 40, 0 ,80]

print(zip(x,y))
print(list(zip(x,y)))     # need to save zip() in a data structure to have a visibility on it.

<zip object at 0x7b8700008cc0>
[('villian', 150), ('hero', 100), ('lion', 40), ('pig', 0), ('dog', 80)]

In [ ]:
headlines = ["Local Bear Eaten by Man",
             "Legislature Announces New Laws",
             "Peasant Discovers Voilence Inherent in System",
             "Cat Rescues Fireman Struck in Tree",
             "Brave Knight Runs Away",
             "Papperbok Review: Totally Triffic"]

i = 0
x = ""
while i < len(headlines):          # coversion of list of strings to a string.
  x += headlines[i] + " "
  i += 1

print(x[:141])

In [ ]:
# (1)
x_coord = [23, 53, 2, -12, 95, 103, 14, -5]
y_coord = [677, 233, 405, 433, 905, 376, 432, 445]
z_coord = [4, 16, -6, -42, 3, -6, 23, -1]
lables =  ["F", "J" , "A", "Q", "Y", "B", "W", "X"]

p = zip(lables,x_coord,y_coord,z_coord)      # zip(list,etc..) :- attaches each element of the list each element of other list in index wise order.

l = []
for lables,x,y,z in p:
  l.append((f"{lables}: {x}, {y}, {z}"))     # created a new list and added(append) the formatted elements [or] add
                                             # the formatted elements to exsisting list (2)
print(l)

#                     [or]

# for i in range(len(lables)):
#  print(f"{lables[i]}: {x_coord[i]}, {y_coord[i]}, {z_coord[i]}")

['F: 23, 677, 4', 'J: 53, 233, 16', 'A: 2, 405, -6', 'Q: -12, 433, -42', 'Y: 95, 905, 3', 'B: 103, 376, -6', 'W: 14, 432, 23', 'X: -5, 445, -1']

In [ ]:
# (2)
x_coord = [23, 53, 2, -12, 95, 103, 14, -5]
y_coord = [677, 233, 405, 433, 905, 376, 432, 445]
z_coord = [4, 16, -6, -42, 3, -6, 23, -1]
lables =  ["F", "J" , "A", "Q", "Y", "B", "W", "X"]

i =0
for l,x,y,z in zip(lables,x_coord,y_coord,z_coord):
  lables[i] = (f"{l}: {x}, {y}, {z} ")
  i += 1
print(lables)

['F: 23, 677, 4 ', 'J: 53, 233, 16 ', 'A: 2, 405, -6 ', 'Q: -12, 433, -42 ', 'Y: 95, 905, 3 ', 'B: 103, 376, -6 ', 'W: 14, 432, 23 ', 'X: -5, 445, -1 ']

In [ ]:
cast_names = ["Joey Tribbiani","Monica Geller","Chandler Bing", "Ross Geller","Phoebe Buffay "]
cast_heights = [172, 168, 172, 166, 170]

cast = dict(zip(cast_names,cast_heights))
print(cast)

In [ ]:
data = ((0,1,2),(3,4,5),(6,7,8),(9, 10, 11))

a,b,c = tuple(zip(*data))    # unzips by making each element in sublist to pair

data_transpose = [a,b,c]

print(data_transpose)

In [ ]:
cast = ["Barney Stinson", "Robin Scherbatsky", "Ted Mosby", "Lily Aldrin","Marshall Eriksen"]
height = [150, 100, 40, 0 ,80]

i = 0                                                                                                                           # code for, not in list but only strings as output
l = []
for x,y in zip(cast,height):                                                                                                    #           x = list(zip(cast,height))
  l.append((f"{x} {y}"))                            # created a new list and add the elements in a favorable formatted way      # [or]      for i,j in x:
  i += 1                                                                                                                        #             print(i,j)

print(l)
                                                                         #    [or]

print()
                                    # add the formatted elements in the "cast" list itself
for a,b in enumerate(cast):          # enumerate(list,tuple..etc..): gives the (index, element) of each element in the "list" that id given in the
  cast[a] = b + " " + str(height[a])

print(cast)                                             # NOTE: zip(range(len(l)),l)  ==  enumerate(l)     (where l --> list)

['Barney Stinson 150', 'Robin Scherbatsky 100', 'Ted Mosby 40', 'Lily Aldrin 0', 'Marshall Eriksen 80']

['Barney Stinson 150', 'Robin Scherbatsky 100', 'Ted Mosby 40', 'Lily Aldrin 0', 'Marshall Eriksen 80']

## **zip, enumerate, break and continue**

### **List Comprehensions**

In [ ]:
cities = ["new york city","mountain view","chicago","los angeles"]

captalized_cities = [city.title() for city in cities]                 # SHORTCUT:   for "for"

print(captalized_cities)

['New York City', 'Mountain View', 'Chicago', 'Los Angeles']

In [ ]:
square = [x**2 for x in range(9) if x % 2 == 0 ]               # for "for" + "if"

double = [x*2 if x % 2 == 0 else x + 10 for x in range(9)]      # for "for" + "if" + "else"

print(square)
print(double)

[0, 4, 16, 36, 64]
[0, 11, 4, 13, 8, 15, 12, 17, 16]

### **Some useful methods in string:**
###**x.split("default"): can split string into lists at where the "default" is.**
###**x.replace("x","y"): replaces x by y in the string.**

In [ ]:
name = ["Barney Stinson", "Robin Scherbatsky", "Ted Mosby", "Lily Aldrin","Marshall Eriksen"]

first_name = [i.split()[0].lower() for i in name]

print(first_name)

['barney', 'robin', 'ted', 'lily', 'marshall']

In [ ]:
multiple_3 = [i*3 for i in range(1,21) ]

print(multiple_3)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60]

In [ ]:
scores = {"Deku":70,
          "Bakugo":35,
          "Tenya":82,
          "Shoto":23,
          "All Might":98}

passed = [i for i,j in scores.items() if j >= 65]

print(passed)

['Deku', 'Tenya', 'All Might']

## **Functions in Python**

In [ ]:
def product(a = 5,b = 8):    # used when user gives no argument, it takes the default value 5,8 given by us
  print(a*b)

product(3,4)
product(6)
product()

In [ ]:
# print statement does not save the data(output) but only temprary stores the output, unlike return keyword which permanently store the output

def sum1(a = 0,b = 0):    #  def sum(a = 0,b = 0):
  print(a + b)           #    return a + b

x = sum1(3,6)

print(x)                  # print(x)               # output:  9
print(type(x))            # pritn(type(x))         # output: <class int>

9
None
<class 'NoneType'>

### NOTE: "return" can only be used in functions

In [ ]:
def population_density(population,land_area):
  return population/land_area

t1 = population_density(10,1)
print(f"result: {t1}")

t2 = population_density(864816,121.4)
print(f"result: {t2}")

In [ ]:
def readable_timedelta(d):
  return (f"week(s): {d // 7} day(s): {d % 7}")

x = readable_timedelta(10)
print(x)

In [ ]:
def t(a, b):
  return a*b, a + b

x,y =  t(4,6)            # unpacks the return outputs accordingly(in order like in list)

print(x)
print(y)

In [ ]:
add = lambda x,y : x + y    # returns x + y (lambda function -> shortcut for defining function)

x = add(4,7)
print(x)

In [ ]:
def mean(l):
  return sum(l) / len(l)

lst = [[233,765,564,433],
       [755,313,530,955],
       [655,872,642,836],
       [336,464,286,367]]

p = list(map(mean, lst))         # map(): performs the function on each element of the list/tuple or etc..

print(p)

[498.75, 638.25, 751.25, 363.25]

In [ ]:
sum1(6,7)

13

### NOTE: When you define a function in 1 collab notebook in 1 cell, it will be stored to and can be used in all cells in that notebook.

## **Docstrings and variable scope**

In [ ]:
lstnum = [[1,8,3],[4,9,7]]

def add2(lstnum):
  lstnum.append(2)
  return lstnum

x = list(map(add2,lstnum))
print(x)

[[1, 8, 3, 2], [4, 9, 7, 2]]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')